/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_slytechs_library_NativeLibrary */

#ifndef _Included_com_slytechs_library_NativeLibrary
#define _Included_com_slytechs_library_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: cache */
/* Inaccessible static: negativeSymbols */
/*
 * Class:     com_slytechs_library_NativeLibrary
 * Method:    dlopen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_slytechs_library_NativeLibrary_dlopen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_slytechs_library_NativeLibrary
 * Method:    dlsymbol
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_slytechs_library_NativeLibrary_dlsymbol
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
