/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_slytechs_library_NativeLibraryReference */

#ifndef _Included_com_slytechs_library_NativeLibraryReference
#define _Included_com_slytechs_library_NativeLibraryReference
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: lock */
/* Inaccessible static: pending */
/* Inaccessible static: gc */
/*
 * Class:     com_slytechs_library_NativeLibraryReference
 * Method:    dlclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_slytechs_library_NativeLibraryReference_dlclose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
