/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_slytechs_library_JNISymbol */

#ifndef _Included_com_slytechs_library_JNISymbol
#define _Included_com_slytechs_library_JNISymbol
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: NOT_FOUND_SYMBOL */
/*
 * Class:     com_slytechs_library_JNISymbol
 * Method:    registerSymbol
 * Signature: (Ljava/lang/Class;JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_slytechs_library_JNISymbol_registerSymbol
  (JNIEnv *, jclass, jclass, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
